version: '3'

services:
  postgres:
    image: 'postgres:15-alpine'
    working_dir: /application
    volumes:
        - '.:/application'
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=employees
    ports:
        - '29004:5432'

networks:
  postgres-compose-network:
    driver: bridge
    